# Generated by Django 3.2.8 on 2021-11-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211103_0429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regist',
            new_name='signup',
        ),
    ]
