# Generated by Django 3.2.7 on 2021-11-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_signup_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('friend_name', models.CharField(max_length=20)),
                ('월', models.CharField(max_length=20)),
                ('화', models.CharField(max_length=20)),
                ('수', models.CharField(max_length=20)),
                ('목', models.CharField(max_length=20)),
                ('금', models.CharField(max_length=20)),
            ],
        ),
    ]
