# Generated by Django 3.2.7 on 2021-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='금',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='목',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='수',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='월',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='화',
        ),
        migrations.AddField(
            model_name='friend',
            name='fri',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='mon',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='my_name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='thu',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='tue',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='wed',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend_name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
