# Generated by Django 3.2.7 on 2021-11-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20211117_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=20)),
                ('friend_name', models.CharField(max_length=20)),
                ('mon', models.CharField(max_length=20)),
                ('tue', models.CharField(max_length=20)),
                ('wed', models.CharField(max_length=20)),
                ('thu', models.CharField(max_length=20)),
                ('fri', models.CharField(max_length=20)),
            ],
        ),
    ]
