# Generated by Django 3.2.7 on 2021-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='friend_name',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='my_name',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='excel',
            name='wed',
        ),
        migrations.AddField(
            model_name='excel',
            name='fri1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='excel',
            name='friend_name1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='excel',
            name='mon1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='excel',
            name='my_name1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='excel',
            name='thu1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='excel',
            name='tue1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='excel',
            name='wed1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
