# Generated by Django 3.2.7 on 2021-11-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20211123_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excel',
            old_name='fri1',
            new_name='fri',
        ),
        migrations.RenameField(
            model_name='excel',
            old_name='friend_name1',
            new_name='friend_name',
        ),
        migrations.RenameField(
            model_name='excel',
            old_name='mon1',
            new_name='mon',
        ),
        migrations.RenameField(
            model_name='excel',
            old_name='my_name1',
            new_name='my_name',
        ),
        migrations.RenameField(
            model_name='excel',
            old_name='thu1',
            new_name='thu',
        ),
        migrations.RenameField(
            model_name='excel',
            old_name='tue1',
            new_name='tue',
        ),
        migrations.RenameField(
            model_name='excel',
            old_name='wed1',
            new_name='wed',
        ),
    ]
