# Generated by Django 3.2.7 on 2021-11-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20211123_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='fri',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='excel',
            name='mon',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='excel',
            name='thu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='excel',
            name='tue',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='excel',
            name='wed',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
