# Generated by Django 3.2.7 on 2021-11-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20211123_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='excel',
            new_name='excel_db',
        ),
    ]
