# Generated by Django 3.2.10 on 2021-12-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_excel_excel_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='fri',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='mon',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='thu',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='tue',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='wed',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
