# Generated by Django 3.2.10 on 2021-12-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_member_ssgpw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='etaPw',
            field=models.CharField(max_length=200),
        ),
    ]
