# Generated by Django 3.2.10 on 2021-12-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_member_etapw'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='privkey',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pubkey',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
