# Generated by Django 3.2.10 on 2022-01-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20211229_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='privkey',
        ),
        migrations.RemoveField(
            model_name='member',
            name='pubkey',
        ),
    ]
